title: phd-urfu
author: Savelii Pototskii
email: savelii.pototskii@gmail.com
url: https://phd.savalione.com # root address of the site
baseurl: ""
description: "phd-urfu"

# permalink: /:slug.html
permalink: /:categories/:slug

favicon: "logo.png"
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Google analytics
analytics_google: G-WYW0KGK158

# Collections
collections:
  philosophy_general:
    output: true
    sort_by: number
    permalink: /philosophy/general/:slug
  philosophy_humanities:
    output: true
    sort_by: number
    permalink: /philosophy/humanities/:slug
  philosophy_lectures:
    output: true
    sort_by: number
    permalink: /philosophy/lectures/:slug
  philosophy_technical:
    output: true
    sort_by: number
    permalink: /philosophy/technical/:slug
  philosophy:
    output: true
    permalink: /philosophy/:slug

collections_dir: src

# Exclude files
exclude:
  - CHANGELOG.md
  - README.md
  - README.ru.md
